// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCSnRGux_C0mv5B98jGE_SrCZk8YxgCOY',
    appId: '1:734438758739:web:bc30b1a5a18fcf527129a6',
    messagingSenderId: '734438758739',
    projectId: 'eict-spaces',
    authDomain: 'eict-spaces.firebaseapp.com',
    storageBucket: 'eict-spaces.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBsYCI6UYXnbCQFiittyGLtXmODLr85rU',
    appId: '1:734438758739:android:8888dbae84ea3db17129a6',
    messagingSenderId: '734438758739',
    projectId: 'eict-spaces',
    storageBucket: 'eict-spaces.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Bpn4de1GfF6fNUqSW1D8JpXjsT6qdEg',
    appId: '1:734438758739:ios:9ac6af5c9fbc7a397129a6',
    messagingSenderId: '734438758739',
    projectId: 'eict-spaces',
    storageBucket: 'eict-spaces.appspot.com',
    androidClientId: '734438758739-35avh7o70fbcf23mv2n2lmkf43d963cs.apps.googleusercontent.com',
    iosClientId: '734438758739-tiipuaaol9nm7fcfc9m0417rgn6vi54f.apps.googleusercontent.com',
    iosBundleId: 'com.example.eictSpacesAdm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5Bpn4de1GfF6fNUqSW1D8JpXjsT6qdEg',
    appId: '1:734438758739:ios:9ac6af5c9fbc7a397129a6',
    messagingSenderId: '734438758739',
    projectId: 'eict-spaces',
    storageBucket: 'eict-spaces.appspot.com',
    androidClientId: '734438758739-35avh7o70fbcf23mv2n2lmkf43d963cs.apps.googleusercontent.com',
    iosClientId: '734438758739-tiipuaaol9nm7fcfc9m0417rgn6vi54f.apps.googleusercontent.com',
    iosBundleId: 'com.example.eictSpacesAdm',
  );
}
